module.exports = [
  {
    name: "petal",
    base: "base-light.css",
    vars: "root-petal.css",
    label: "🌸 花瓣",
    accent: "#e8859b",
    bg: "#fdf9fa",
    text: "#333333",
  },
  {
    name: "petal-dark",
    default: true,
    base: "base-dark.css",
    vars: "root-petal-dark.css",
    label: "🌸 花瓣·暗夜",
    accent: "#ffaac8",
    bg: "#332c32",
    hue: 350,
    text: "#eeeeee",
  },
  {
    name: "mist",
    base: "base-light.css",
    vars: "root-mist.css",
    label: "☁️ 雾蓝",
    accent: "#92A8B3",
    bg: "#F2F4F5",
    text: "#333333",
  },
  {
    name: "mist-dark",
    base: "base-dark.css",
    vars: "root-mist-dark.css",
    label: "💠 雾蓝·暗夜",
    accent: "#9bb9d7",
    bg: "#333840",
    hue: 240,
    text: "#eeeeee",
  },
  {
    name: "verdant",
    base: "base-light.css",
    vars: "root-verdant.css",
    label: "🍃 草木",
    accent: "#A0B0A7",
    bg: "#F2F5F3",
    text: "#333333",
  },
  {
    name: "verdant-dark",
    base: "base-dark.css",
    vars: "root-verdant-dark.css",
    label: "🌲 草木·暗夜",
    accent: "#99b3a3",
    bg: "#202522",
    hue: 160,
    text: "#eeeeee",
  },
  {
    name: "stone",
    base: "base-light.css",
    vars: "root-stone.css",
    label: "🧱 暖石",
    accent: "#B1A49E",
    bg: "#F5F3F1",
    text: "#333333",
  },
  {
    name: "stone-dark",
    base: "base-dark.css",
    vars: "root-stone-dark.css",
    label: "🪨 暖石·暗夜",
    accent: "#dab39b",
    bg: "#33302e",
    text: "#eeeeee",
  },
  {
    name: "wheat",
    base: "base-light.css",
    template: "root-stone.css",
    label: "🌾 麦穗",
    description: "Morandi Wheat (Muted Straw)",
    colors: {
      accent: "oklch(60% 0.065 82)",
      bg: "oklch(97% 0.006 82)",
      surface: "oklch(95% 0.008 82)",
      "surface-2": "oklch(92% 0.012 82)",
      text: "oklch(25% 0.018 82)",
      "text-semi": "oklch(45% 0.018 82)",
      "code-token-keyword": "oklch(55% 0.1 72)",
      "code-token-string": "oklch(58% 0.11 135)",
      "code-token-number": "oklch(60% 0.12 45)",
      "code-token-blue": "oklch(58% 0.12 240)",
      "code-muted-rgb": "124, 118, 104",
    },
  },
  {
    name: "wheat-dark",
    base: "base-dark.css",
    template: "root-stone-dark.css",
    label: "🌾 麦穗·暗夜",
    description: "Morandi Wheat Dark (Toasted Straw)",
    hue: 82,
    colors: {
      accent: "oklch(74% 0.075 82)",
      bg: "oklch(22% 0.018 82)",
      surface: "oklch(29% 0.02 82)",
      "surface-2": "oklch(35% 0.025 82)",
      text: "oklch(96% 0.01 82)",
      "text-semi": "oklch(82% 0.018 82)",
      "code-bg": "oklch(16% 0.01 82)",
      "code-token-keyword": "oklch(78% 0.1 75)",
      "code-token-string": "oklch(75% 0.1 145)",
      "code-token-number": "oklch(78% 0.1 45)",
      "code-token-blue": "oklch(72% 0.12 240)",
      "code-muted-rgb": "140, 135, 120",
    },
  },
  {
    name: "ripple",
    base: "base-light.css",
    vars: "root-ripple.css",
    label: "🌊 涟漪",
    accent: "#5fa8b2",
    bg: "#fcfdfe",
    text: "#333333",
  },
  {
    name: "ripple-dark",
    base: "base-dark.css",
    vars: "root-ripple-dark.css",
    label: "🌊 涟漪·暗夜",
    accent: "#9bd7da",
    bg: "#262d2e",
    text: "#eeeeee",
  },
  {
    name: "cinnabar",
    base: "base-light.css",
    vars: "root-cinnabar.css",
    label: "🧧 丹红",
    accent: "#d74b4b",
    bg: "#fbf2f2",
    text: "#333333",
  },
  {
    name: "cinnabar-dark",
    base: "base-dark.css",
    vars: "root-cinnabar-dark.css",
    label: "🏮 丹红·暗夜",
    accent: "#dc5050",
    bg: "#2b2525",
    hue: 25,
    text: "#eeeeee",
  },
  {
    name: "sage",
    base: "base-light.css",
    vars: "root-sage.css",
    label: "🌿 鼠尾草",
    accent: "#8a9a5b",
    bg: "#fcfef8",
    text: "#333333",
  },
  {
    name: "sage-dark",
    base: "base-dark.css",
    vars: "root-sage-dark.css",
    label: "🌿 鼠尾草·暗夜",
    accent: "#b0b98c",
    bg: "#2b2f28",
    hue: 115,
    text: "#eeeeee",
  },
  {
    name: "spring",
    base: "base-light.css",
    vars: "root-spring.css",
    label: "🪻 紫语",
    accent: "#A873C4",
    bg: "#fcf9fd",
    text: "#333333",
  },
  {
    name: "spring-dark",
    base: "base-dark.css",
    vars: "root-spring-dark.css",
    label: "🔮 紫语·暗夜",
    accent: "#bfa9f5",
    bg: "#3B3640",
    text: "#eeeeee",
  },
];
